{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tunlease.fullname" . }}
  labels:
    {{- include "tunlease.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ printf "%s(/|$)(.*)" .Values.ingress.path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tunlease.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
